const clients = [
  { id: 1, company: 'Harbour & Co.', industry: 'Hospitality', contact: 'Tia Rangi', email: 'tia@harbourandco.nz', notes: 'Quarterly social campaign and hero brand film.', initials: 'H&', color: '#b7d9ff', resources: 12 },
  { id: 2, company: 'Koru Wellness', industry: 'Health & wellbeing', contact: 'Aroha Te Rangi', email: 'aroha@koruwellness.co.nz', notes: 'Launch content for the new studio programme.', initials: 'K', color: '#ffc9dc', resources: 8 },
  { id: 3, company: 'Rimu Collective', industry: 'Property', contact: 'Finn McLeod', email: 'finn@rimucollective.nz', notes: 'Monthly property walkthroughs and reels.', initials: 'R', color: '#c9fa49', resources: 21 },
  { id: 4, company: 'Pōhutukawa Studio', industry: 'Retail', contact: 'Mia Chen', email: 'mia@pohutukawastudio.nz', notes: 'Summer lookbook production.', initials: 'P', color: '#ffb184', resources: 6 },
  { id: 5, company: 'Northland Escapes', industry: 'Tourism', contact: 'Jordan Blake', email: 'jordan@northlandescapes.nz', notes: 'Destination video series.', initials: 'NE', color: '#d6cbff', resources: 17 },
];
let currentView = 'dashboard'; let selectedClientId = 1; let editingId = null; let libraryFilter = 'All resources';
const app = document.querySelector('#app'); const crumbs = document.querySelector('#crumbs'); const dialog = document.querySelector('#client-dialog'); const form = document.querySelector('#client-form');
const esc = s => String(s).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const getClient = id => clients.find(c => c.id === Number(id));
function resourceCards(client) { const media = [['a','Brand film — first cut.mp4','Video • 2:34'],['b','Behind the scenes selects.mp4','Video • 0:46'],['c','Campaign stills.zip','Photos • 28 files']]; return media.map(([cls,name,meta]) => `<article class="resource"><div class="thumb ${cls}">${client.company}</div><div class="resource-info"><strong>${name}</strong><small>${meta}</small></div></article>`).join(''); }
function dashboard() { return `<section class="page"><div class="title-row"><div><p class="eyebrow">MONDAY, 17 AUGUST</p><h1>Kia ora, Maia.</h1><p class="subtitle">Here’s what’s moving across the studio today.</p></div><button class="button" data-add><span class="plus">+</span> Add client</button></div><div class="stats"><div class="stat-card"><div class="label">ACTIVE CLIENTS</div><div class="number">${clients.length}</div><div class="hint"><b>+1</b> added this month</div></div><div class="stat-card"><div class="label">LIVE PROJECTS</div><div class="number">8</div><div class="hint"><b>3</b> awaiting review</div></div><div class="stat-card"><div class="label">TOTAL ASSETS</div><div class="number">${clients.reduce((a,c)=>a+c.resources,0)}</div><div class="hint"><b>+12</b> uploaded this week</div></div></div><div class="dashboard-grid"><section class="card"><div class="card-header"><h2>Projects in motion</h2><button class="text-link" data-go="library">View library →</button></div><div class="project"><div class="poster one"></div><div><strong>Harbour winter campaign</strong><small>Harbour & Co. · Brand film</small></div><span class="status review">IN REVIEW</span></div><div class="project"><div class="poster two"></div><div><strong>Studio launch series</strong><small>Koru Wellness · Social</small></div><span class="status editing">EDITING</span></div><div class="project"><div class="poster three"></div><div><strong>Coastal living, episode 04</strong><small>Northland Escapes · Video series</small></div><span class="status ready">READY</span></div></section><section class="card"><div class="card-header"><h2>Recent activity</h2></div><div class="activity"><div class="activity-item"><span class="dot"></span><div><p><b>Tia Rangi</b> left feedback on Harbour winter campaign</p><time>24 minutes ago</time></div></div><div class="activity-item"><span class="dot"></span><div><p><b>4 files</b> added to Koru Wellness</p><time>2 hours ago</time></div></div><div class="activity-item"><span class="dot"></span><div><p><b>Finn McLeod</b> approved the Rimu walkthrough</p><time>Yesterday</time></div></div></div></section></div></section>`; }
function clientCard(c) { return `<article class="client-card" data-client="${c.id}"><div class="client-card-top"><div class="client-logo" style="background:${c.color}">${esc(c.initials)}</div><span class="tag">ACTIVE</span></div><h2>${esc(c.company)}</h2><p>${esc(c.industry)}</p><div class="client-meta"><span>${esc(c.contact)}</span><span>${c.resources} ASSETS</span></div></article>`; }
function clientsView() { return `<section class="page"><div class="title-row"><div><p class="eyebrow">CLIENT DIRECTORY</p><h1>Clients</h1><p class="subtitle">A home for every relationship, project and file.</p></div><button class="button" data-add><span class="plus">+</span> Add client</button></div><div class="filterbar"><input class="search" id="client-search" placeholder="Search clients…"/><button class="filter">All industries ▾</button><span class="subtitle">${clients.length} clients</span></div><div class="client-grid" id="client-grid">${clients.map(clientCard).join('')}</div></section>`; }
function profileView() { const c = getClient(selectedClientId); if(!c) return clientsView(); return `<section class="page"><button class="text-link" data-go="clients">← All clients</button><div class="profile-banner"><div class="client-logo" style="background:${c.color}">${esc(c.initials)}</div><div><h1>${esc(c.company)}</h1><p>${esc(c.industry)} · Client since August 2026</p></div><div class="profile-actions"><button class="button secondary" data-edit="${c.id}">Edit client</button></div></div><div class="profile-info"><section class="card"><div class="card-header"><h2>Client details</h2></div><div class="detail-list"><div><span>Primary contact</span><strong>${esc(c.contact)}</strong></div><div><span>Email</span><strong>${esc(c.email)}</strong></div><div><span>Notes</span><strong>${esc(c.notes)}</strong></div></div></section><section class="card"><div class="card-header"><h2>Recent resources</h2><button class="text-link" data-go="library">View all →</button></div><div class="resource-grid">${resourceCards(c)}</div></section></div></section>`; }
function libraryView() { const c = getClient(selectedClientId); const filters = ['All resources','Videos','Photos','Documents']; return `<section class="page"><div class="title-row"><div><p class="eyebrow">ASSET MANAGEMENT</p><h1>Content library</h1><p class="subtitle">Search, review and share your production work.</p></div><button class="button">↑ Upload files</button></div><div class="library-layout"><aside class="card library-side">${filters.map(x=>`<button data-filter="${x}" class="${libraryFilter===x?'active':''}">${x}<span>${x==='All resources'?clients.reduce((a,v)=>a+v.resources,0):x==='Videos'?32:x==='Photos'?24:8}</span></button>`).join('')}</aside><section class="card"><div class="library-head"><div><h2>${libraryFilter}</h2><small>Showing recent items for ${c.company}</small></div><button class="filter">Newest first ▾</button></div><div class="resource-grid">${resourceCards(c)}${resourceCards(getClient(2))}</div></section></div></section>`; }
function render() { document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView)); crumbs.textContent = `WORKSPACE / ${currentView==='profile'?'CLIENTS / CLIENT PROFILE':currentView.toUpperCase()}`; app.innerHTML = currentView==='dashboard'?dashboard():currentView==='clients'?clientsView():currentView==='profile'?profileView():libraryView(); bindPage(); }
function bindPage() { document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>{currentView=x.dataset.go;render()}); document.querySelectorAll('[data-add]').forEach(x=>x.onclick=openNew); document.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>openEdit(x.dataset.edit)); document.querySelectorAll('[data-client]').forEach(x=>x.onclick=()=>{selectedClientId=x.dataset.client;currentView='profile';render()}); const search=document.querySelector('#client-search'); if(search) search.oninput=e=>{document.querySelector('#client-grid').innerHTML=clients.filter(c=>`${c.company} ${c.industry} ${c.contact}`.toLowerCase().includes(e.target.value.toLowerCase())).map(clientCard).join('');bindPage()}; document.querySelectorAll('[data-filter]').forEach(x=>x.onclick=()=>{libraryFilter=x.dataset.filter;render()}); }
function openNew(){editingId=null;form.reset();document.querySelector('#form-kicker').textContent='NEW CLIENT';document.querySelector('#form-title').textContent='Add a client';dialog.showModal()}
function openEdit(id){const c=getClient(id);editingId=c.id;for(const key of ['company','industry','contact','email','notes'])form.elements[key].value=c[key];document.querySelector('#form-kicker').textContent='CLIENT PROFILE';document.querySelector('#form-title').textContent='Edit client';dialog.showModal()}
form.addEventListener('submit',e=>{e.preventDefault();if(!form.checkValidity())return;const data=Object.fromEntries(new FormData(form));if(editingId){Object.assign(getClient(editingId),data)}else{const initials=data.company.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();clients.push({id:Date.now(),...data,initials,color:'#c9fa49',resources:0})}dialog.close();currentView='clients';render()});
document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()});render();
